### ISSUE TITLE
Partial responses for PATCH

### ISSUE THREAD

**Issue by rnewman** [mozilla-services/readinglist#138]
When you upload a record, either full (POST) or partial (PATCH), the server returns the full server record.

In the case of the former, it makes sense — the server fills in a lot of fields, including important stuff like the ID.

In the case of the latter, it's consistent, but makes life harder for the client in two ways:

* The client always has to apply the server result in full, which is a full-size DB UPDATE, with a full-size download first.
* The client can't tell whether its upload "succeeded" — that is, whether all of the fields it tried to set ended up with the values it specified.

An ideal would be that a client does no extra work if its fire-and-forget request 'succeeded'. That means two things:

* The server record changed to reflect precisely the fields uploaded.
* The server record hasn't otherwise changed since it was last downloaded by that client.

If those two things are true, then the client can be confident that it has the same data for that record as the server, without having to download the record again.

I propose either an optional mode or a change to the default: for PATCH, accompanied by some header with a timestamp (If-Modified-Since? If-Unmodified-Since controls conflicts, but I-M-S perhaps not?) the server will return one of two things.

If the record hasn't changed since the provided timestamp, it returns a partial body, containing only:

* Fields that changed as a side-effect of processing: e.g., server last modified.
* Fields that were specified in the request, but were not set to the exact value that was uploaded.

If it has changed since that time, then the server returns the whole record, as it currently does.

Thoughts?

**Comment by leplatrem** [comment]
I see what you mean (I think of read_position mainly).

Currently:
* ``If-Unmodified-Since`` raises 412 if collection/record has changed meanwhile in every end-points (and verbs)
* ``If-Modified-Since`` is used in collection/record read end-points (GET) to return 304 responses

Your suggestion to use ``If-Modified-Since`` in PATCH to filter out fields that haven't change makes sense to me, and does not seem to twist/bend too much its semantics.

If most of us agree, we could do it easily with something like this:

```python
if request.if_modified_since is None or old_record.last_modified > request.if_modified_since:
     return new_record  #full
else:
     filtered_fields = {}
     for field, value in new_record.items():
         # Side-effects
         if old_record[field] != new_record[field]:
             filtered_fields[field] = value
         # Not set to provided value
         if request.body[field] != new_record[field]:
             filtered_fields[field] = value
     return filtered_fields
```

**Comment by Natim** [comment]
Hi @rnewman 

I have been implementing your request here: https://github.com/mozilla-services/readinglist/pull/150

Also we have some concerns about this.

In an ideal world, when you do a PATCH you get back the full record and apply it back to your database.

In that case you do not need any extra work because you just apply the new record to your DB.

    db.set(record_id, record)

In case of a diff you need more work on the client because you need to get the record, update the fields from the diff and set back the record.

    record = db.get(record_id)
    for field in changes:
        record[field] = changes[field]
    db.set(record_id, record)

Also it adds lots of place where a problem may occurs when doing the synchronization on server side.

For the readinglist use case, the user will not have a large number of articles to update, also the content of the article will not be in the article body but we will probably have an URL to a CDN to let the client get back the content.

With that in mind, could you explain why having the diff of the modifications can help the client?

**Comment by Natim** [comment]
Note that #150 has been merged but I am still interesting on figuring out why it is easier for you to get the diff rather than just applying the given record to your database.

**Comment by rnewman** [comment]
That's not how databases work on client platforms. We get much closer to the database, rather than a record abstraction. (Or, rather, the record -> row mapping is our own.)

We can pass in any columns: not a complete set. Something like:

```
final ContentValues values = new ContentValues();
for (String key : record.keySet()) {
    values.put(key, record.getString(key));
}
db.update(selection, args, values);
```

Having the server return a complete record is wasteful: the client has to download the entire record, rather than just the relevant columns, transform all of them, and apply all of them. And in theory the delta is equivalent to applying the whole thing. For many updates — ones where no fields change as a side-effect, and the record hasn't previously changed since the client downloaded it — the only thing to change will be the server `last_modified` time! Pulling down and applying a whole record in this case is disrespectful of the user's data allowance and battery.
