### ISSUE TITLE
Deprecation indicators

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/readinglist#18]

**Comment by ametaireau** [comment]
Something else I think we could support is parameter renames.

For instance, for loop we had to change some parameter names at some point. The only way we had to deal with that was to accept both old and new parameters on the server side. That's fine, but then the client don't notice anything.

I would like to have a deprecation channel also report any chages like that. I'm not sure how this should be implemented explicitely, but headers seems a good way to convey such information.

**Comment by ametaireau** [comment]
@rfk in the bug you referred to, you're mentioning "513 GO AWAY", but I cannot find this in Any specification.

As this sounds rather a client error rather than a client one, I feel it should be a 4XX error code.
After a quick review of what's available, I found the `426 / Upgrade Required` one (RFC 2817) which is for TLS upgrade normally.

Maybe we should go for this?

**Comment by rnewman** [comment]
I'd like to keep this narrowly focused on protocol/service-level deprecation — that is, telling a client that it needs to upgrade, or that it needs to tell the user that the service is going away. That's because I don't think we'd build anything more fine-grained than that in all of our clients.

E.g., wrt renames, I can't imagine the client being able to do anything intelligent here above and beyond turning itself off until it upgrades, so I suspect that's how we'd do it: shift to the next version of the protocol, wait a few releases, then have the old protocol endpoint start sending deprecation indicators to clients.

I think "513" was a typo of 503:

```
Hard EOL:  all requests return a 503, with an X-Weave-Alert header that includes a JSON object with code:hard-eol, like this:

    513 GO AWAY
```
As to client error versus server error: I think this is the server refusing to handle a request, rather than the client creating a malformed request.

We found 426, but IIRC it wasn't really suitable — yes, it's for TLS (and thus will misbehave when proxies get in the way, and we probably shouldn't reuse it for a different purpose), but it also means "I can't continue this conversation until you upgrade, and when you do, this URL is still good", while for our purposes we want "I understood you, but I'm refusing to act, and you need to go to a different URL after you upgrade". To me that sounds like a "justified 503", or similar.

**Comment by rfk** [comment]
> you're mentioning "513 GO AWAY", but I cannot find this in Any specification.

Indeed; turns out we made up a new code because none of the existing ones seemed to fit: https://bugzilla.mozilla.org/show_bug.cgi?id=895518#c11

**Comment by rfk** [comment]
(Which doesn't mean we have to keep the made-up code for all eternity, I'd be delighted to see us find something nicer this next go around.)

**Comment by rfk** [comment]
I can see arguments for a service-wide `410 Gone` for example...

**Comment by ametaireau** [comment]
### Renames & Deprecation

About renames and deprecation, shipping a new version of the protocol will work yeah! Though, it's a shift in my thinking: it seems we would be issuing new versions quite often.

To resume:

0. We are using v1 of the procol;
1. We decide to rename `old_fieldname` to `new_fieldname` on our API;
2. We craft a new version of the protocol, v2 because of the change;
3. v1 start sending deprecation indicators to the client, using `soft-eol`;
4. clients are updated to use the new version;
5. after some time, v1 is shutdown and returns `hard-eol`.

We could also patch V1 to support the old *and the new* names, whenever possible (foreward compat).

### Hard-EOL status code

Some 4XX are explicitly returned when the server chose not to fulfill the request, even if they are well formed. That's what 403, 405 and 406 are doing for instance.

The HTTP specs seem to define the use of the 503 as something that should be alleviated after some delay, which is not the case for us.

> The server is currently unable to handle the request due to a temporary overloading or maintenance of the server. The implication is that this is a temporary condition which will be alleviated after some delay. If known, the length of the delay MAY be indicated in a Retry-After header. If no Retry-After is given, the client SHOULD handle the response as it would for a 500 response. 

I wasn't thinking about 410, but it seems to be exactly what we want here:

>  *The requested resource is no longer available* at the server and *no forwarding address is known*. This condition is expected to be considered permanent.
> 
> The 410 response is primarily intended to assist the task of web maintenance by notifying the recipient that the resource is intentionally unavailable and that the server owners desire that remote links to that resource be removed. *It is not necessary to mark all permanently unavailable resources as "gone" or to keep the mark for any length of time -- that is left to the discretion of the server owner.*

So just returning a 410 at the root would do the job, but having this for all sub-resources doesn't seem like something hard, so I believe we got what we are looking for!

**Comment by ametaireau** [comment]
https://github.com/mozilla-services/readinglist/pull/117
