### ISSUE TITLE
Convert CHANGELOG.rst to CHANGELOG.md?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/readinglist#245]
Currently the [CHANGELOG.rst](https://github.com/mozilla-services/readinglist/blob/49e2465138d3b3d2950e4acbdad4a9768779d781/CHANGELOG.rst) file is an .rst file, which means none of the issue numbers are linked.

Not sure if we want to convert that to a CHANGELOG.md file so GitHub auto links all the issue numbers to their respective repos.

**Comment by leplatrem** [comment]
Using .rst is like a convention in the python packaging. Maybe I'm wrong, but personnally, I don't think it is worth breaking conventions for linking issues :]

We could : 

* Use the release page https://github.com/mozilla-services/readinglist/releases
* Change the CHANGELOG file to link full URLs instead of github shortcuts

Which one would you prefer ?

**Comment by Natim** [comment]
Yes the PYthon Package Index only understand reStructuredText, I agree with @leplatrem 

I am not sure it is a big deal not to have link when looking ad CHANGELOG.rst since we've got the release page with them already.

**Comment by ametaireau** [comment]
Some solutions for this exist, [in the form of converting the rst to markdown](http://stackoverflow.com/a/26737672/147077) before pushing to PyPI, but I don't think we want to follow this path.

Not having to write the links manually is something that helps us writing the changelog fast so I wouldn't want to change this (unless we automate it)

**Comment by pdehaan** [comment]
OK, cool. Closing as "lets not do that".
