### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by rnewman** [mozilla-services/readinglist#25]
#13 and #14 raise the question of how to fetch large numbers of items.

We can expect some number of users on day one to have hundreds of items. For illustration, there are a number of folks on the mobile team who have more than 1500 items in their current Pocket queue.

In ordinary operation — frequently connected — we can expect downloaded changesets to be small; a handful of new and changed items in each fetch.

In protracted disconnected operation we'll need batching for uploads, which is #2.

That leaves us worrying about first-time download on a device, and subsequent downloads after a very protracted disconnected period (or after an import).

We can approach this in one of a few ways.

1. Ignore the problem. Always maintain a full list of items on the client. Fetch everything in one go. After all, the metadata for even a thousand items will probably only be a few hundred KB. This is fine for initial development, but probably not enough for a global release — even a few hundred KB is too much in surprisingly many locales.

2. Ignore the problem except for downloads. Always maintain a full list of items on the client, but fetch items in batches. This is easy if the server supports sorting (already desirable: #14) and one more thing: range queries over some immutable attribute. E.g.,

```
articles/?sort=-stored_on&stored_on_less_than=123456
```

This solves some reliability/interrupted download issues, but still triggers significant space and bandwidth costs immediately after install. (What would you think if Gmail downloaded the headers for every message to your phone after signing in?)

3. Go fully server-canonical, and expect most clients to have only a partial cache of the articles that are stored on the server. For example, clients might not bother fetching metadata about archived articles until the user tries to see that list. Pocket falls into this category: it'll fetch new batches of articles as you scroll through your list.

This requires much the same support from the server, but imposes additional smarts on the client.

I think we should go with (1) during development, then shift to (2) or (3) as soon as we can.

**Comment by leplatrem** [comment]
Thanks @rfk for all these details :) It allowed us to iterate clearly with Richard!

We'll go for the continuation token approach.

In order to give us flexibility regarding server-side implementation, we thought we could just return a ``Next-Page`` response header, containing the full URL of the next page.
This URL would contain every necessary parameters for the server to obtain the pagination context (and raise expiration it if necessary). The client wouldn't bother with anything else than ``limit`` and ``Next-Page``.

Nevertheless, how the client behaves on expired pagination is unclear.

When the continuation token of a pagination expires (some record in the collection changed meanwhile), we will return an error (like 412). But then how does the client resolve the expiration and resume pagination ?

(*let's say a user scrolling down in her archived items, while an other device archives an item*)

Thanks for your insights :)

**Comment by rnewman** [comment]
>
> When the continuation token of a pagination expires (some record in the
> collection changed meanwhile), we will return an error (like 412). But then
> how does the client resolve the expiration and resume pagination ?
>
> (*let's say a user scrolling down in her archived items, while an other
> device archives an item*)
>
>
One option is that the server is smart enough to resume the pagination
whenever possible, preserving the original intent. This is more work than
just invalidate-on-any-change, but strictly better. For example: changes to
items already paged over are ignored (they'll be picked up later in an
incremental sync, or the user has already scrolled past those items!);
changes to items not yet seen are fine (they'll likewise be picked up
later); added items can be worked in to, or appended to, the sequence;
removed items don't matter; etc.

Another option is that we allow a client to supply an 'after' parameter.
Say we're sorting on 'xx', a numeric field. We see our last item has
'xx=52'. When our pagination is interrupted, we start again with
limit=20&last_xx=52, and this effectively lets us resume where we left off.
(The server can also do this with some additional bookkeeping: see above,
but of course this can leave garbage on the server.)

Another is to allow the client to make a pagination request and say "I've
seen all of these IDs". It would expect the server to return a cursor over
all other items.

The final option is for the client to start again from scratch. That's not
a huge deal, because we expect pagination to only be used interactively or
for initial syncs.

**Comment by Natim** [comment]
http://use-the-index-luke.com/no-offset

**Comment by Natim** [comment]
I have been scratching my head on this problem this last three days and my conclusion is that we have two solutions:

 - Either we use continuation_tokens and we remove the collection sorting feature
 - Or we use OFFSET / LIMIT if we want sorting.

For me both can work because user will not have a huge number of articles and we won't need server side sorting for the readinglist.

**Comment by Natim** [comment]
Following #14 where @rnewman was saying:

> fetching unread items first, and thus being able to display them more quickly

I think this can be fixed by asking the ``unread=True`` collection and then asking ``unread=False``.

If we can get rid of sorting (saying that all collection will be order last modified first) that will helps build a scalable solution for pagination.

**Comment by Natim** [comment]
I might have an alternative solution. I will think furthermore about it.

**Comment by leplatrem** [comment]
If the algorithm pagination is too complex, we can have an intermediary implementation (stupid, inefficient, limited, ...), and iterate later in the month.

The advantage of having the ``Next-Page`` header is that clients won't require any change if we change|improve the pagination mecanism.

The offset approach isn't efficient, but a collection of articles isn't like browsing history of millions of people :)

**Comment by rnewman** [comment]
>
> The advantage of having the Next-Page header is that clients won't
> require any change if we change|improve the pagination mecanism.
>
Exactly. Feel free to iterate on exactly what the URL is and does; it's
even acceptable if it returns dupes or (if you really must) skips items,
though I expect that with min/max arguments you can avoid that and just
ship something inefficient!

**Comment by rfk** [comment]
> The advantage of having the Next-Page header is that clients won't require any
> change if we change|improve the pagination mecanism.

Yep, exactly this - you can even use different pagination techniques for the sorted-vs-unsorted case if you need to.

**Comment by Natim** [comment]
Well I finally figure out what I was trying to solve.

I wrote this to explain and I am going to write a blog post about this: https://etherpad.mozilla.org/pagination-token-with-sorting

**Comment by rnewman** [comment]
I added some discussion at the bottom of the etherpad — I might have got
the wrong end of the stick, so please let me know!

**Comment by Natim** [comment]
> Isn't this more complicated than necessary? Or am I misunderstanding?

I think you get it all. If we don't care of sorting during pagination we don't need all that.

The point of doing that is to be able to do pagination on sorting. Hopefully for us Databases are much more good and efficient at filtering than at offsetting.

Also please note that if you just sort by -last_modified it will only be a '<' where clause.
The problem I was trying to solve is to be able to do pagination with sorting attributes without duplicates.

The race when insertion occurs during collection fetching is handled with the ``If-Unmodified-Since`` header that will return a 412 in case the collection changed between pages.

The good thing is that it was complicated once but it keep simple if clients don't need sorting and pagination at the same time. Also it works with complex sorting in a efficient way.
